version: '3.9'
services:
 radarr:
  container_name: radarr
  restart: unless-stopped
  volumes:
    - ./config/Radarr:/config
    - ./downloads/Movies:/downloads/Movies
  environment:
   - PUID=${PUID}
   - PGID=${PGID}
   - TZ=${TZ}
  ports:
   - 7878:7878
  image: linuxserver/radarr

 sonarr:
  container_name: sonarr
  restart: unless-stopped
  volumes:
    - ./config/Sonarr:/config
    - ./downloads/TVShows:/downloads/TVShows
  environment:
   - PUID=${PUID}
   - PGID=${PGID}
   - TZ=${TZ}
  ports:
   - 8989:8989
  image: linuxserver/sonarr

 lidarr:
  container_name: lidarr
  restart: unless-stopped
  volumes:
    - ./config/Lidarr:/config
    - ./downloads/Music:/downloads/Music
  environment:
   - PUID=${PUID}
   - PGID=${PGID}
   - TZ=${TZ}
  ports:
   - 8686:8686
  image: linuxserver/lidarr

 jackett:
  container_name: jackett
  restart: unless-stopped
  volumes:
   - ./config:/config
  environment:
   - PUID=${PUID}
   - PGID=${PGID}
   - TZ=${TZ}
  ports:
   - 9117:9117
  image: linuxserver/jackett

 autobrr:
  container_name: autobrr
  image: ghcr.io/autobrr/autobrr:latest
  restart: unless-stopped
  user: ${PUID}:${PGID}
  environment:
   - TZ=${TZ}
  volumes:
   - ./config/autobrr:/config
  ports:
   - 7474:7474

 flaresolverr:
  image: ghcr.io/flaresolverr/flaresolverr:latest
  container_name: flaresolverr
  environment:
   - LOG_LEVEL=${LOG_LEVEL:-info}
   - LOG_HTML=${LOG_HTML:-false}
   - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
   - TZ=${TZ}
  restart: unless-stopped
  ports:
   - 8191:8191

 prowlarr:
  image: lscr.io/linuxserver/prowlarr:latest
  container_name: prowlarr
  environment:
   - PUID=${PUID}
   - PGID=${PGID}
   - TZ=${TZ}
  volumes:
   - ./config/prowlarr:/config
  restart: unless-stopped
  ports:
   - 9696:9696

 cross-seed:
  image: crossseed/cross-seed:latest
  container_name: cross-seed
  user: ${PUID}:${PGID}
  volumes:
   - ./config/cross-seed:/config
   - ./config/qBittorrent/data/BT_backup:/torrents
   - ./downloads:/downloads
  command: daemon
  restart: unless-stopped

 qbittorrent:
  image: qbittorrentofficial/qbittorrent-nox:latest
  container_name: qbittorrent-nox
  environment:
   - PUID=${PUID}
   - PGID=${PGID}
   - TZ=${TZ}
   - QBT_WEBUI_PORT=8080
  stop_grace_period: 30m
  tmpfs:
   - /tmp
  volumes:
   - ./config:/config
   - ./downloads:/downloads
  ports:
   - ${QBT_WEBUI_PORT}:${QBT_WEBUI_PORT}
   - ${PORT_FORWARD_PORT}:6881/tcp
   - ${PORT_FORWARD_PORT}:6881/udp
  restart: unless-stopped

 qbittools:
  image: registry.gitlab.com/alexkm/qbittools
  container_name: qbittools
  volumes:
   - ./config/qBittorrent/config:/qBittorrent
  command: reannounce -C /qBittorrent/qBittorrent.conf
  restart: unless-stopped
